# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "[](bold #a6e3a1) $directory$git_branch$git_status [➜](bold #a6e3a1) "

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[username]
style_user = "#a6e3a1 bold"
style_root = "black bold"
# format = "user: [$user]($style) "
disabled = false
show_always = true
